name: BSM Prop Rental
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json", "images-to-md.js"]
permalink: /props/:title
baseurl: '/bsm-prop-rental'